# Generated by Django 4.2.7 on 2023-11-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PhysicianPatient",
        ),
    ]
