# Generated by Django 4.2.7 on 2023-11-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "SUBMITTED"),
                    ("PENDING", "PENDING"),
                    ("REJECTED", "REJECTED"),
                    ("SUCCESS", "SUCCESS"),
                ],
                default="SUBMITTED",
                max_length=50,
            ),
        ),
    ]
